// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ownhjoapprdswyyimwtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93bmhqb2FwcHJkc3d5eWltd3R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNzY2MDIsImV4cCI6MjA2MTc1MjYwMn0.UsA3VAV4yEmTq7GANgEkvf0DUrfnRZv6l2z-daRchXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);